""" Write a Python program to calculate the total monthly salary of an employee by adding the fixed salary and incentive amount """
#coding section  

basic_salary = float(input("Enter the basic salary: "))
incentive = float(input("Enter the incentive amount: "))
total_salary = basic_salary + incentive

print("Total Monthly Salary:", total_salary)
"""output: Enter the basic salary: 25000
Enter the incentive amount: 8500
Total Monthly Salary: 33500.0"""
